# 00. PyTorch Fundamentals
Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.2+cpu


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()` -> https://pytorch.org/docs/stable/tensors.html

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.shape

torch.Size([2])

In [7]:
# Matrix
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
MATRIX[1]

tensor([ 9, 10])

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [11]:
TENSOR.ndim

3

In [12]:
TENSOR.shape

torch.Size([1, 3, 3])

In [13]:
TENSOR[0][1][2]

tensor(6)

### Random Tensors

Random tensors are important because the way many neural networks learn is that they start with tensors full of random number and then adjust those random numbers to better represent the data

`Start with random number -> look at data -> update random numbers -> update random numbers`

In [14]:
# Create a random tensor of shape/size (3,4)
random_tensor = torch.rand(3,4,)
random_tensor

tensor([[0.3916, 0.6221, 0.0431, 0.4310],
        [0.4766, 0.0080, 0.2561, 0.8730],
        [0.6692, 0.9868, 0.3442, 0.7801]])

In [15]:
random_tensor.ndim

2

In [16]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224,224)) # colour channels (RGB), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [17]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
# Create a tensor of all zeros
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
ones.dtype

torch.float32

### Create a range of tensors and tensors-like

In [20]:
# Use torch.range()
one_to_ten = torch.arange(0,10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [22]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=None, device=None, requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [23]:
float_32_tensor.dtype

torch.float32

### Getting information from tensors

1. Tensors not right datatype - to get a datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [24]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor    

tensor([[0.7654, 0.6539, 0.9451, 0.7990],
        [0.5651, 0.4484, 0.4308, 0.9038],
        [0.2634, 0.2121, 0.6730, 0.7647]])

In [25]:
# Find out details about some tensor
print(some_tensor.dtype)
print(some_tensor.shape)
print(some_tensor.device)

torch.float32
torch.Size([3, 4])
cpu


### Manipulating Tensors (tensor operations)

Tensor Operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [26]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
print(tensor + 10)
print(torch.add(tensor, 10))

tensor([11, 12, 13])
tensor([11, 12, 13])


In [27]:
# Multiply tensor by 10
print(tensor * 10)
print(torch.mul(tensor, 10))

tensor([10, 20, 30])
tensor([10, 20, 30])


In [28]:
# Subtract tensor by 10
print(tensor - 10)
print(torch.sub(tensor, 10))

tensor([-9, -8, -7])
tensor([-9, -8, -7])


In [29]:
# Divide tensor by 10
print(tensor / 10)
print(torch.div(tensor, 10))

tensor([0.1000, 0.2000, 0.3000])
tensor([0.1000, 0.2000, 0.3000])


### Matrix multiplication

Two main ways of performing multiplcation in neural networks and deep learning.

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
    * `(3,2) @ (3, 2)` won't work
    * `(2,3) @ (3, 2)` will work
    * `(3,2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
   * `(2,3) @ (3,2) -> (2,2)`
   * `(3,2) @ (2,3) -> (3,3)`
   

In [30]:
mat1 = torch.rand(3,2)
mat2 = torch.rand(3,2)
print(mat1)
print(mat2)

tensor([[0.0387, 0.9183],
        [0.5815, 0.6150],
        [0.0993, 0.0965]])
tensor([[0.2404, 0.4122],
        [0.9193, 0.3550],
        [0.1085, 0.4791]])


In [31]:
torch.matmul(mat1, mat2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [32]:
mat1 = torch.rand(3,2)
mat2 = torch.rand(2,3)
print(mat1)
print(mat2)

tensor([[0.0649, 0.0065],
        [0.4779, 0.4013],
        [0.8537, 0.2333]])
tensor([[0.9034, 0.4049, 0.3261],
        [0.0534, 0.1468, 0.0579]])


In [33]:
torch.matmul(mat1, mat2)

tensor([[0.0589, 0.0272, 0.0215],
        [0.4532, 0.2524, 0.1791],
        [0.7837, 0.3800, 0.2919]])

In [34]:
# Element wise multiplication
torch.mul(tensor, tensor)

tensor([1, 4, 9])

In [35]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

### One of the most common errors in deep learning: shape errors

In [36]:
# Shapes for matrix multiplication
tensor_A = torch.rand(size=(3,2))
print(tensor_A)

tensor_B = torch.rand(size=(3,2))
print(tensor_B)

tensor([[0.1584, 0.4709],
        [0.5293, 0.9756],
        [0.5230, 0.9617]])
tensor([[0.4466, 0.6059],
        [0.6070, 0.0151],
        [0.1740, 0.1094]])


In [37]:
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using transpose.

A **transpose** switches the axes or dimensions of a given tensor.

In [38]:
print(tensor_B)
print(tensor_B.T)

tensor([[0.4466, 0.6059],
        [0.6070, 0.0151],
        [0.1740, 0.1094]])
tensor([[0.4466, 0.6070, 0.1740],
        [0.6059, 0.0151, 0.1094]])


In [39]:
# The matrix multiplcationn operation works when tensor_b is transposed
torch.matmul(tensor_A, tensor_B.T)

tensor([[0.3561, 0.1032, 0.0791],
        [0.8275, 0.3360, 0.1988],
        [0.8163, 0.3320, 0.1962]])

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [40]:
# Create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [41]:
# Find the min
x.min()

tensor(1)

In [42]:
# Find the max
x.max()

tensor(91)

In [43]:
# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [44]:
# Find the sum
x.sum()

tensor(460)

### FInding the positional min and max

In [45]:
# min and min index
x.min(), x.argmin(), x[x.argmin()]

(tensor(1), tensor(0), tensor(1))

In [46]:
# max and max index
x.max(), x.argmax(), x[x.argmax()]

(tensor(91), tensor(9), tensor(91))

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of a certain shape but keep the same memory as the original tensor
* Stacking - Concatenates a secombine multiple tensors on top of each other (vertical stack) or side by side (horizontal stack)
* Squeeze - Removes all `1` dimension from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the imput with dimensions permuted (swapped) in a certain way

In [62]:
#Create a tensor
import torch

x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [63]:
#Add a dimension
#a new object
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [64]:
#Change view
#shares memory with x
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [58]:
#change z changes x

In [65]:
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [66]:
x_reshaped[:,0] = 10
x_reshaped,x
#thought this would show them different but it didnt?

(tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]),
 tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]))

In [74]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [85]:
# torch.squeeze() removes all single dimensions from a target tensor
x = torch.zeros(2, 1, 2, 1, 2)
x,x.size()
y = torch.squeeze(x) # removes all
y.size()
y = torch.squeeze(x, 1) # removes at index
x,x.size(),y.size()

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]),
 torch.Size([2, 2, 1, 2]))

In [93]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dimension (dim)
y = torch.unsqueeze(x, dim=1)
x.shape,y.shape

(torch.Size([2, 1, 2, 1, 2]), torch.Size([2, 1, 1, 2, 1, 2]))

In [97]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # heright, widthh, colour

#Permute original tensor to rearrange the axis (dim) order
x_new = x_original.permute(2,0,1)
x_original.shape, x_new.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [99]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [110]:
x[0][0], x[0,:,1]

(tensor([1, 2, 3]), tensor([2, 5, 8]))

In [118]:
x[0,1:, 1]

tensor([5, 8])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

PyTorch has functionality to interact with it.

* Data in NumPy to use in PyTorch -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [123]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor, array.dtype, tensor.dtype, torch.arange(1.0, 8.0).dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 dtype('float64'),
 torch.float32,
 torch.float32)

In [124]:
array = array + 1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [126]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor, tensor.dtype, numpy_tensor.dtype,

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 torch.float32,
 dtype('float32'))

In [127]:
tensor = tensor + 1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (take the random out of random)

How a neural network learns:

`start with a random number -> tensor operations -> update random numbers to try and make them of the data -> again -> again

To reduce randomness in neural networks and PyTorch comes the concept of a **random seed**

Random seed gives a starting point for the randomness and will always produce the same *randomness*

In [135]:
import torch

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
random_tensor_A,random_tensor_B,random_tensor_A==random_tensor_B

(tensor([[0.5251, 0.1851, 0.5258, 0.6363],
         [0.7075, 0.7046, 0.8430, 0.7858],
         [0.3789, 0.3135, 0.7345, 0.5579]]),
 tensor([[0.2080, 0.1277, 0.7779, 0.7330],
         [0.8097, 0.0132, 0.4823, 0.9856],
         [0.0282, 0.3292, 0.7643, 0.3558]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [145]:
RANDOM_SEED = 1234
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
random_tensor_A,random_tensor_B,random_tensor_A==random_tensor_B

(tensor([[0.0290, 0.4019, 0.2598, 0.3666],
         [0.0583, 0.7006, 0.0518, 0.4681],
         [0.6738, 0.3315, 0.7837, 0.5631]]),
 tensor([[0.7749, 0.8208, 0.2793, 0.6817],
         [0.2837, 0.6567, 0.2388, 0.7313],
         [0.6012, 0.3043, 0.2548, 0.6294]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

## Running tensors and PyTorch objects on GPU
GPUs are faster at computing numbers than CPU

https://pytorch.org/get-started/locally/

In [146]:
# nvidia gpu
!nvidia-smi

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.


### Check for GPU connection to PyTorch


In [148]:
# check for GPU access with PyTorch
import torch
torch.cuda.is_available(), torch.cuda.device_count()

(False, 0)

In [150]:
# Device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
torch.device(device)
device

'cpu'

## Putting tensors and models on the GPU
The reason we would want our tensors/models on the GPU is because using a GPU results in faster computations

In [152]:
import torch
tensor = torch.tensor([1,2,3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

### Move tensors back to CPU

In [153]:
tensor.cpu().numpy()

array([1, 2, 3], dtype=int64)