# 00. PyTorch Fundamentals
Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.2+cpu


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()` -> https://pytorch.org/docs/stable/tensors.html

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.shape

torch.Size([2])

In [7]:
# Matrix
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
MATRIX[1]

tensor([ 9, 10])

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [11]:
TENSOR.ndim

3

In [12]:
TENSOR.shape

torch.Size([1, 3, 3])

In [13]:
TENSOR[0][1][2]

tensor(6)

### Random Tensors

Random tensors are important because the way many neural networks learn is that they start with tensors full of random number and then adjust those random numbers to better represent the data

`Start with random number -> look at data -> update random numbers -> update random numbers`

In [14]:
# Create a random tensor of shape/size (3,4)
random_tensor = torch.rand(3,4,)
random_tensor

tensor([[0.9178, 0.9381, 0.4079, 0.7458],
        [0.6641, 0.5553, 0.4922, 0.8679],
        [0.1761, 0.9398, 0.3534, 0.6573]])

In [15]:
random_tensor.ndim

2

In [16]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224,224)) # colour channels (RGB), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [17]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
# Create a tensor of all zeros
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
ones.dtype

torch.float32

### Create a range of tensors and tensors-like

In [20]:
# Use torch.range()
one_to_ten = torch.arange(0,10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [22]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=None, device=None, requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [23]:
float_32_tensor.dtype

torch.float32

### Getting information from tensors

1. Tensors not right datatype - to get a datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [24]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor    

tensor([[0.1636, 0.0090, 0.5280, 0.6819],
        [0.2532, 0.2376, 0.4284, 0.6123],
        [0.8576, 0.0858, 0.0945, 0.4212]])

In [25]:
# Find out details about some tensor
print(some_tensor.dtype)
print(some_tensor.shape)
print(some_tensor.device)

torch.float32
torch.Size([3, 4])
cpu


### Manipulating Tensors (tensor operations)

Tensor Operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [26]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
print(tensor + 10)
print(torch.add(tensor, 10))

tensor([11, 12, 13])
tensor([11, 12, 13])


In [27]:
# Multiply tensor by 10
print(tensor * 10)
print(torch.mul(tensor, 10))

tensor([10, 20, 30])
tensor([10, 20, 30])


In [28]:
# Subtract tensor by 10
print(tensor - 10)
print(torch.sub(tensor, 10))

tensor([-9, -8, -7])
tensor([-9, -8, -7])


In [29]:
# Divide tensor by 10
print(tensor / 10)
print(torch.div(tensor, 10))

tensor([0.1000, 0.2000, 0.3000])
tensor([0.1000, 0.2000, 0.3000])


### Matrix multiplication

Two main ways of performing multiplcation in neural networks and deep learning.

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
    * `(3,2) @ (3, 2)` won't work
    * `(2,3) @ (3, 2)` will work
    * `(3,2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
   * `(2,3) @ (3,2) -> (2,2)`
   * `(3,2) @ (2,3) -> (3,3)`
   

In [30]:
mat1 = torch.rand(3,2)
mat2 = torch.rand(3,2)
print(mat1)
print(mat2)

tensor([[0.2512, 0.4292],
        [0.3006, 0.7771],
        [0.9515, 0.2591]])
tensor([[0.4969, 0.7892],
        [0.4488, 0.9877],
        [0.8056, 0.1298]])


In [31]:
torch.matmul(mat1, mat2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
mat1 = torch.rand(3,2)
mat2 = torch.rand(2,3)
print(mat1)
print(mat2)

In [ ]:
torch.matmul(mat1, mat2)

In [ ]:
# Element wise multiplication
torch.mul(tensor, tensor)

In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

### One of the most common errors in deep learning: shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.rand(size=(3,2))
print(tensor_A)

tensor_B = torch.rand(size=(3,2))
print(tensor_B)

In [ ]:
torch.matmul(tensor_A, tensor_B)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using transpose.

A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
print(tensor_B)
print(tensor_B.T)

In [ ]:
# The matrix multiplcationn operation works when tensor_b is transposed
torch.matmul(tensor_A, tensor_B.T)

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(1, 100, 10)
x

In [ ]:
# Find the min
x.min()

In [ ]:
# Find the max
x.max()

In [ ]:
# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

In [ ]:
# Find the sum
x.sum()

### FInding the positional min and max

In [ ]:
# min and min index
x.min(), x.argmin(), x[x.argmin()]

In [ ]:
# max and max index
x.max(), x.argmax(), x[x.argmax()]